### ISSUE TITLE
Not updating since 20220327.1

### ISSUE THREAD

**Issue by 21Development** [bimmerconnected/ha_custom_component#35]
The releases after 20220117.1 (327, 331 & 401) seem to have stopped updating the sensors correctly. If I restart HA, the location updates but then if the vehicle is moved, it no longer updates the location, until the next time I restart HA.

I also noticed several switches have been added, including ones that I don’t think are supported such as aircon on/off and hitting “Refresh from cloud” or “Find vehicle” results is server errors.

I have re-installed 20220117.1 and will update to see if that is still working when the car moves again. **[confirmed: This version still updates correctly]**

example error:
Logger: bimmer_connected.account
Source: /usr/local/lib/python3.9/site-packages/bimmer_connected/account.py:312 
First occurred: 9:44:45 AM (1 occurrences) 
Last logged: 9:44:45 AM

MyBMW API error '500 Server Error: Internal Server Error for url: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1649061880017&tireGuardMode=ENABLED': {"error":{"statusCode":500,"error":"Internal Server Error","message":"An unknown exception occurred"},"correlationId":"[removed]"}

**Comment by mibo-wb-gh** [comment]
BMW Connected Drive BETA / 20220401.1
Home Assistant 2022.3.8
BMW 330ex touring

Same problem here:
- Only updating when the integration is reloaded or HA is restarted
- Find Vehicle throws the following error:

The My BMW App always shows the correct location
Attached please find the error log regarding the "Find Vehicle" function

[Error_Log_BMW_FindVehicle.txt](https://github.com/bimmerconnected/ha_custom_component/files/8425594/Error_Log_BMW_FindVehicle.txt)

**Comment by Yixi** [comment]
Same problem..

**Comment by rikroe** [comment]
Thanks for reporting, both issues (device tracker not updating & unable to execute buttons) are fixed with the latest release [20220410.1](https://github.com/bimmerconnected/ha_custom_component/releases/tag/20220410.1).

**Comment by 21Development** [comment]
Thanks - I can’t see the update in HACS, will test when it’s available (or do we need to update manually?)

It seemed like the 500 Server errors were as a consequence of there being API calls to unsupported features, i.e. there is no option in the iOS app to switch on/off AirCon but it became available here after 327 version. Other buttons that started showing after 327 were; “Flash Lights, Sound Horn, Find Vehicle & Refresh from cloud”

**Comment by mibo-wb-gh** [comment]
Thanks a million😉 Update via HACS worked without a problem. Will check the device tracker tomorrow.

Best Regards,
Michael


-------- Ursprüngliche Nachricht --------
Von: rikroe ***@***.***>
Datum: 10.04.22 18:57 (GMT+01:00)
An: bimmerconnected/ha_custom_component ***@***.***>
Cc: mibo-wb-gh ***@***.***>, Comment ***@***.***>
Betreff: Re: [bimmerconnected/ha_custom_component] Not updating since 20220327.1 (Issue #35)


Thanks for reporting, both issues (device tracker not updating & unable to execute buttons) are fixed with the latest release 20220410.1<https://github.com/bimmerconnected/ha_custom_component/releases/tag/20220410.1>.

**Comment by rikroe** [comment]
Please also update to 20220410.4, as there were some other small bugs introduced. 

And thanks for being beta testers :)

**Comment by mibo-wb-gh** [comment]
device_tracker is functioning again !

Thx, for all your hard work your putting into this !

Best Regards,
Michael


Von: rikroe ***@***.***>
Gesendet: Montag, 11. April 2022 09:38
An: bimmerconnected/ha_custom_component ***@***.***>
Cc: mibo-wb-gh ***@***.***>; Comment ***@***.***>
Betreff: Re: [bimmerconnected/ha_custom_component] Not updating since 20220327.1 (Issue #35)


Please also update to 20220410.4, as there were some other small bugs introduced.

And thanks for being beta testers :)

**Comment by rikroe** [comment]
Closing this as the `notify` issue is tracked it #39

**Comment by mibo-wb-gh** [comment]
Update 20220410.4

***@***.***

Looks good !

At the moment my car has zero electric power left, that is why it shows „Unbekannt“ for „…remaining_range_electric“ and „…remaining_battery_percent“

It would be great if it showed „0 km“ and „0%“ but that would just be „nice to have“ 😊

Best Regards,

Michael


Von: rikroe ***@***.***>
Gesendet: Montag, 11. April 2022 09:38
An: bimmerconnected/ha_custom_component ***@***.***>
Cc: mibo-wb-gh ***@***.***>; Comment ***@***.***>
Betreff: Re: [bimmerconnected/ha_custom_component] Not updating since 20220327.1 (Issue #35)


Please also update to 20220410.4, as there were some other small bugs introduced.

And thanks for being beta testers :)
